# mysql
spring:
    datasource:
        url: jdbc:mysql://148.70.187.110:3306/ssm_demo
        username: root
        password: XXXXX
        driver-class-name: com.mysql.jdbc.Driver
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size:  3
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.bestoyc.ssmdemo.mapper
